name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linters
      run: flake8 src/

    - name: Run tests
      run: pytest -q --tb=short tests/
      env:
        API_KEY: $MY_SECRET

    - name: Security audit
      run: pip-audit
      
